import "./globals.css";

export const metadata = {
  title: "alttextbot — accessible alt text, instantly",
  description:
    "Upload an image, get screen-reader-ready alt text and a caption, generated by an Amazon Bedrock vision model.",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
