import { Uploader } from "@/components/Uploader";

export default function Home() {
  return (
    <main>
      <header className="topbar">
        <div className="brand">
          <span className="brand-mark" aria-hidden="true" />
          <span className="brand-name">alttextbot</span>
        </div>
        <span className="badge">Amazon Bedrock · Claude 3 Haiku</span>
      </header>

      <section className="hero">
        <span className="eyebrow">Accessibility tooling</span>
        <h1>
          Every image deserves
          <br />
          <em>a description.</em>
        </h1>
        <p className="lede">
          Drop in an image and get back concise, screen-reader-ready alt text
          plus a fuller caption in seconds — generated by a vision model, not
          guessed by a template.
        </p>
      </section>

      <Uploader />

      <section className="how">
        <span className="section-label">How it works</span>
        <ol className="how-steps">
          <li>
            <span className="step-index">01</span>
            <p>
              The browser sends your image as multipart form data to{" "}
              <code>POST /api/alt-text</code>.
            </p>
          </li>
          <li>
            <span className="step-index">02</span>
            <p>
              The Next.js route handler base64-encodes it and invokes a
              Bedrock vision model with a prompt constrained to strict JSON
              output.
            </p>
          </li>
          <li>
            <span className="step-index">03</span>
            <p>
              Alt text and a caption come back and render instantly, ready to
              copy into your markup.
            </p>
          </li>
        </ol>
      </section>

      <footer>
        built by <a href="https://hellocamie.com">camie</a> · Next.js + Amazon
        Bedrock
      </footer>
    </main>
  );
}
